// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;

namespace RankBeggarAI
{
    public partial class RankBeggar
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(@"SentimentText", @"SentimentText")
                                    .Append(mlContext.Transforms.Concatenate(@"Features", @"SentimentText"))
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"Sentiment", @"Sentiment"))
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))
                                    .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(l1Regularization: 0.03125F, l2Regularization: 1.42300534933383F, labelColumnName: @"Sentiment", featureColumnName: @"Features"))
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}