name: Build and Package website

on:
  push:
    branches:
      - 'main'
    paths:
      - 'BreganTwitchBot.Web/**'
      - 'BreganTwitchBot.Infrastructure/**'
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Build Docker Image
      run: |
        docker build -t twitchbotweb -f BreganTwitchBot.Web/Dockerfile .
        
    - name: Save Docker Image
      run: |
        docker save twitchbotweb > twitchbotweb.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: twitchbotweb.tar
        target: ${{ secrets.TARGET }}
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            docker stop twitchbotweb || true && docker rm twitchbotweb || true
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i ${{ secrets.TARGET }}twitchbotweb.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 5004:80 --mount type=bind,source="${{ secrets.FILE_PATH }}",target=/app/Logs --env BTBConnString='${{ secrets.ENV }}' --name twitchbotweb twitchbotweb:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm ${{ secrets.TARGET }}twitchbotweb.tar