name: Build and Package website

on:
  push:
    branches:
      - 'main'
    paths:
      - 'BreganTwitchBot.Web/**'
      - 'BreganTwitchBot.Infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Build Docker Image
      run: |
        cd bregantwitchbot.web/
        docker build -t twitchbotwebsite .
        
    - name: Save Docker Image
      run: |
        docker save twitchbotwebsite > twitchbotwebsite.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: twitchbotwebsite.tar
        target: ${{ secrets.TARGET }}
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            docker stop twitchbotwebsite || true && docker rm twitchbotwebsite || true
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i ${{ secrets.TARGET }}twitchbotwebsite.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 3002:3000 --name twitchbotwebsite twitchbotwebsite:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm ${{ secrets.TARGET }}twitchbotwebsite.tar