name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
      - name: Set Execution Policy (ultra-safe)
        run: Set-ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f BreganTwitchBot/Dockerfile -t 192.168.1.100:5000/bregantwitchbotcore:latest .

      - name: Push Docker image
        run: docker push 192.168.1.100:5000/bregantwitchbotcore:latest
